### PR TITLE
Adding solutions of the tasks

### PR DESCRIPTION
**Pull request by Alexander759**
- [x] Creating new folder for solutions
- [x] Creating new folder with my name
- [x] Adding my files in it
- [ ] Adding gitignore (not sure it works properly, someone should check it)

### CODE REVIEW

**Comment by Alexander759** [comment]
Yeah sorry, I will try to send only the .cpp files in folders

**Comment by SirLex** [comment]
@Alexander759 Please review what you have pushed and what not. There are changes only to .gitignore file as far as I can see -> remove those

**Comment by Alexander759** [comment]
I think I added it in another pull request. Check this one [https://github.com/SirLex/UP/pull/10](url) if there is a problem may be just directly the branch [https://github.com/Alexander759/UP/tree/solutions](url). If there is a problem again just write me.

**Comment by Alexander759** [comment]
I added another pull request [here](https://github.com/SirLex/UP/pull/10).
If there is a problem may be just the branch  [here](https://github.com/Alexander759/UP/tree/solutions).
If still there is a problem write me again

**Pull request closed without merging**
