### PR TITLE
Pract.05: Add 1-12 | Velina Souroujon

### PR DESCRIPTION
**Pull request by VelinaSouroujon**
Velina Souroujon
3 6MI0600415

### CODE REVIEW

**Review by AtanasHrist0v — CHANGES_REQUESTED** [review]
Please review the instructions [here](https://github.com/SirLex/UP/blob/main/Git%20&%20GitHub%20Tutorials/README.md), point 5, last bullet point.

**Comment by SirLex** [comment]
Great work! But please delete the README.md file so we can merge it

**Comment by AtanasHrist0v** [comment]
While removing the Sem.05/Pract.05/Student's Solutions/Velina Souroujon/README.md, you have also somehow removed the Sem.05/Pract.05/README.md. This creates a conflict and I can't merge your branch. Please sync this branch or manually add the original Sem.05/Pract.05/README.md.

**Comment by AtanasHrist0v** [comment]
You have copied an old README.md that had typos and has long been fixed. Please replace it with the newest version of the file or manually fix the numeration for the tasks in the README.md.

**Review by AtanasHrist0v — APPROVED** [review]

**Pull request merged**
